### PR TITLE
Version2 Support

### PR DESCRIPTION
**Pull request by CashWasabi**
This Branch is working with Python2 and Python3.

### CODE REVIEW

**Comment by raul5660** [comment]
i don't mean to sound like an ass but do you know what changes you made and understand what you were doing?

**Comment by Marc3lox** [comment]
I did a huge cleanup all over those files. I hope it's more obvious now which changes i made.

**Comment by jekyc** [comment]
Hi Marc3lox,

Thanks for the pull request and the work put into porting wig to python 2.

I've updated issue https://github.com/jekyc/wig/issues/12 with a general comment on the two current pull requests. As they both solve the issue of supporting python 2 by creating completely separate classes for the python versions, I don't think that the result will be easy maintainable. I temporary suggestion could be to link to your fork in wig and the readme, just until a more permanent solution is found. Is this something you'd be interested in? 

On a side note, I noticed that you're using the 'requests' lib. wig also made use of it in previous versions, but I decided to create a custom lib for it, as I ran into issues on some versions of 'requests' (can't remember which, but IIRC I think it was the version shipped with the Kali Linux distro at some point). I'd therefore prefer wig to not be dependent on any third party libs.

**Comment by roberth1988** [comment]
Hi Jekyc,

but developing a custom lib comes with higher maintenance efforts. I am using requests quite long with different versions => its clear that sometime some bugs pop in but in my opinion its better to use a well and active maintained library instead of a custom-made one.

**Comment by Marc3lox** [comment]
Hey Jekyc,
even though I think "requests" would be a better decision on the long run i also managed to get a version running which supports wig on python2 without completly seperate classes and without requests. The only dependency is the pip module "futures" which enables "concurrent.futures" for python2. You can look at it in the branch called "wig-python2-support".

**Comment by jekyc** [comment]
Hi,

While I agree that using the 'requests' lib would be nice, I don't like the idea that a distro provide version 'requests' can make wig non-functional. I might decide to go back to 'requests' lib at a later point, but for now, I think sticking to wig's 'request2' the best solution. This lib is only about 350 lines, of which a large part would still be needed if wig were to switch to 'requests'.  

@Marc3lox: I like the approach, and that the changes do not require separate libs. I've compared the two versions, but it is a bit difficult because tabs are changed to spaces (I know that spaces are indeed preferred over tabs according to PEP-8 (http://legacy.python.org/dev/peps/pep-0008/#tabs-or-spaces)). Is possible for you to change them back ?

**Comment by Marc3lox** [comment]
Hey,
sure! As soon as I'm free I'll convert it back to tabs.

**Pull request closed without merging**
