### PR TITLE
pip integration

### PR DESCRIPTION
**Pull request by portantier**
I've modified the git structure to allow installations like:

pip install git+https://github.com/portantier/wig

also I've modified some files to permit that the changes works well,

Now, you can import wig from any location, like that:

from wig.wig import wig
w = wig(url='google.com')
w.run()
results = w.get_results()
print(results)

### CODE REVIEW

**Comment by portantier** [comment]
Also, now you can upload the package to 
https://pypi.python.org/pypi
Regards!

**Comment by jekyc** [comment]
Hi portantier!

Thanks for the pull request. It's a great improvement, so I've just merged it. Good catch on the json file extension check :)

**Comment by jekyc** [comment]
It seems I merged too quickly and without testing it properly. I can't seem to get it working without moving 'wig.py' out to the parent folder. 

What steps have you taken to get wig running after the changes ?

**Comment by jekyc** [comment]
I think I've fixed it.

**Comment by portantier** [comment]
OMG, sorry! I've not checked the usage from command line!

Only tested as a function/package! :(

**Pull request merged**
